// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import FlashMessageController from "./flash_message_controller"
application.register("flash-message", FlashMessageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MenuController from "./menu_controller"
application.register("menu", MenuController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import ProblemSortController from "./problem_sort_controller"
application.register("problem-sort", ProblemSortController)

import ProblemStatusColourController from "./problem_status_colour_controller"
application.register("problem-status-colour", ProblemStatusColourController)
